function createTempFolders(tmpFolder)
% make sure all necessary temp folders exist

tmpSubFolders={...
    'seqinfo',...
    'ISall',...
    'Iunsp',...
    'hyp',...
    'hyps',...
    'res',...
    };

for t=1:length(tmpSubFolders)
    tsf=char(tmpSubFolders(t));
    tf=fullfile(tmpFolder,tsf);
    if ~exist(tf,'dir'), mkdir(tf); end
end
